[package]
authors = ["Ballerina"]
distribution = "2201.8.1"
keywords = ["Healthcare", "FHIR", "Endpoint", "r4", "health.fhir.r4.davinciplannet"]
name = "health.fhir.r4.davinciplannet.endpoint"
org = "wso2"
template = true
version = "1.0.0"
