[package]
org = "healthcare"
name = "health.fhir.r4.davinciplannet.organization"
version = "1.0.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Organization", "r4", "health.fhir.r4.davinciplannet"]
template = true
